# Generated by Django 3.1.5 on 2021-01-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ten", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="description",
            field=models.CharField(max_length=5000),
        ),
    ]
